# Generated by Django 5.1.4 on 2024-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryuser",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("unavailable", "Unavailable")],
                default="available",
                max_length=11,
            ),
        ),
    ]
