# Generated by Django 4.1.3 on 2024-12-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
