# Generated by Django 5.1.4 on 2024-12-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliveryuser_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryuser",
            name="status",
        ),
    ]
