# Generated by Django 4.1.3 on 2024-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_deliveryuser_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='deliveryContact',
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
