# Generated by Django 4.1.3 on 2024-12-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customuser_is_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_delivery',
        ),
    ]
