# Generated by Django 4.1.3 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='default_id', max_length=100),
        ),
    ]
