# Generated by Django 5.1.3 on 2024-11-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_comment_comment_id'),
        ('ordering', '0002_delete_ordering'),
    ]

    operations = [
    ]
