# Generated by Django 4.1.3 on 2024-11-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_rename_fooditem_fooditem1_rename_order_order1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order1',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem1',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='orderitem1',
            name='order',
        ),
        migrations.DeleteModel(
            name='FoodItem1',
        ),
        migrations.DeleteModel(
            name='Order1',
        ),
        migrations.DeleteModel(
            name='OrderItem1',
        ),
    ]
