# Generated by Django 4.1.3 on 2024-12-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_comment_id'),
        ('ordering', '0003_merge_0002_comment_comment_id_0002_delete_ordering'),
    ]

    operations = [
    ]
