# Generated by Django 4.1.3 on 2024-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_fooditems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='category',
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='restaurantName',
            field=models.CharField(max_length=50),
        ),
    ]
