# Generated by Django 4.1.3 on 2024-12-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_delivery_contact'),
        ('restaurant', '0011_city_place_state_userlocation_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='place',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='state',
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.city'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.place'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.state'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
