# Generated by Django 5.1.3 on 2024-12-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.city')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.place')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.state')),
            ],
        ),
    ]
